apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/share/nginx
    server: 192.168.2.50

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-nfs-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Gi